export const animalList = [
    {
        name: "Bucks",
        sex: "Samiec",
        breed: "Tricolor",
        image: "https://images.unsplash.com/photo-1617364890779-1bf750360962?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80",
        age: "4-6 mies",
        link: "/adopcja/koty/bucks",
    },
    {
        name: "Missi",
        sex: "Samica",
        breed: "Syberyjski",
        image: "https://www.omlet.com.pl/images/cache/512/323/siberian-cat-out_in_the_snow.jpg",
        age: "2-6 lat",
        link: "",
    },
/*    {
        name: "Puszek",
        sex: "Samiec",
        breed: "Europejski",
        image: "https://trupanion.com/-/media/Trupanion/Images/Breed--Guide--New/Mixed--Breed--Cat/mixed-breed-cat2.jpg?rev=31bbd50aa6b04287bc4f180014f321ca&hash=6FE8D8611C7E4884849351BB57962A6B",
        age: "6 mies - 1 rok",
        link: "",
    },*/
    {
        name: "Kropka",
        sex: "Samica",
        breed: "Europejski",
        image: "https://www.thehappycatsite.com/wp-content/uploads/2017/12/White-Cat-HC-long.jpg",
        age: "6 mies - 1 rok",
        link: "/adopcja/koty/Kropka",
    },
    {
        name: "Żółty",
        sex: "Samiec",
        breed: "Mix",
        image: "https://imgsrv2.voi.id/ReVxNAQQCAkPxSqCIp8GrB79WxD3d0XaDpXvfeM0xu0/auto/1200/675/sm/1/bG9jYWw6Ly8vcHVibGlzaGVycy8xNjQ1MjkvMjAyMjA1MDYxMTUzLW1haW4uY3JvcHBlZF8xNjUxODEyODQ3LmpwZw.jpg",
        age: "2-6 lat",
        link: "",
    },
    {
        name: "Mysza",
        sex: "Samica",
        breed: "Europejski",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Cat_August_2010-4.jpg",
        age: "6-10 lat",
        link: "",
    },
    {
        name: "Bella",
        sex: "Samica",
        breed: "Europejski",
        image: "https://www.omlet.com.pl/images/cache/341/512/Cat-European_Shorthair-a_pretty_european_shorthair_giving_a_cat_pout_for_the_camera.jpg",
        age: "2-6 lat",
        link: "",
    },
/*    {
        name: "Lucky",
        sex: "Samiec",
        breed: "Mix",
        image: "https://i.pinimg.com/736x/2d/f6/db/2df6dbe8ff3e019bc25c43617ba5150d.jpg",
        age: "1-2 lata",
        link: "",
    },
    {
        name: "Miś",
        sex: "Samiec",
        breed: "Tricolor",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/British_Shorthair_tricolore.jpg/220px-British_Shorthair_tricolore.jpg",
        age: "4-6 mies",
        link: "",
    },*/
]
