export const promotion = [
    {
        image: "https://zooart.com.pl/pol_pl_WHISKAS-Sterile-14kg-sucha-karma-dla-kotow-po-sterylizacji-z-kurczakiem-13276_7.jpg",
        title: "WHISKAS Sterile 14kg z kurczakiem",
        price: 115.80,
        link: '/shop/koty/products/sucha-karma/whiskas-sterile-14-kg-z-kurczakiem',
        rating: '4.8',
        producer: 'Whiskas',
        lifePhase: 'dorosły',
        promotion: true,
    },
    {
        image: "https://www.krakvet.pl/pol_pl_Almo-Nature-Adult-z-ryba-oleista-sucha-karma-holistyczna-dla-kota-2-kg-31385_1.jpg",
        title: "ALMO NATURE Holistic Adult z rybą oleistą 2kg",
        price: 45.00,
        link: '/almo-nature-holistic-adult-z-ryba-oleista-2-kg',
        rating: '3.1',
        producer: 'Almo Nature',
        lifePhase: 'dorosły',
        promotion: true,
    },
    {
        image: "https://media.os.fressnapf.com/products-v2/f/7/b/f/f7bffa21025bad257fce06365ea2c407a7b7d6aa_697def108e1a22697d1d833f024146d4c3113b4f.jpg?t=prod_m&f=webp",
        title: "PERFECT FIT (Sensitive 1+) 7kg Bogaty w Indyka",
        price: 109.90,
        link: '/perfect-fit-7-kg-bogaty-w-indyka',
        rating: '5',
        producer: 'Perfect Fit',
        lifePhase: 'dorosły',
        promotion: true,
    },
];
